### ISSUE TITLE
Provider generates invalid Proxy (blank)

### ISSUE THREAD

**Issue by mpholcomb** [pulumi/pulumi-mysql#131]
### What happened?

I am using the `mysql.NewProvider`, without a proxy.  This is returning the following error:

```
     └─ mysql:index:Database    dev_app                         error: could not validate provider configuration: 1 

Diagnostics:
  mysql:index:Database (dev_app):
    error: could not validate provider configuration: 1 error occurred:
        * invalid value for proxy (The proxy URL is not a valid socks url.)
```

I believe this is due to the fact that the proxy is being default to a blank instead of a nil here:
https://github.com/pulumi/pulumi-mysql/blob/master/sdk/go/mysql/provider.go#L43

This is a generated file, so I did not consider making any kind of PR.  For the moment I am just removing that check locally.

### Steps to reproduce

Use the explicit provider, without a Proxy set. 

### Expected Behavior

The provider should not use a proxy, instead of defaulting it to an invalid blank ("") proxy.

### Actual Behavior

Based on the error message, I am assuming the blank proxy is invalid further down the chain.

### Output of `pulumi about`

CLI          
Version      3.46.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME    VERSION
auth0   2.14.0
aws     5.13.0
awsx    1.0.0-beta.11
docker  3.2.0
go      unknown
mysql   3.1.0

Host     
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in go: executable='/home/matt/.gvm/gos/go1.18/bin/go' version='go version go1.18 linux/amd64'

...<removed personal information>...

Dependencies:
NAME                                   VERSION
github.com/pulumi/pulumi-auth0/sdk/v2  2.14.0
github.com/pulumi/pulumi-aws/sdk/v5    5.13.0
github.com/pulumi/pulumi-awsx/sdk      1.0.0-beta.11
github.com/pulumi/pulumi-mysql/sdk/v3  3.1.0
github.com/pulumi/pulumi/sdk/v3        3.39.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by squaremo** [comment]
Thanks for posting this issue @mpholcomb :star:. I'm able to reproduce the problem with this program:

```go
package main

import (
	"github.com/pulumi/pulumi-mysql/sdk/v3/go/mysql"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func main() {
	pulumi.Run(func(ctx *pulumi.Context) error {
		prov, err := mysql.NewProvider(ctx, "mysql", &mysql.ProviderArgs{
			Endpoint: pulumi.String("localhost"),
			Username: pulumi.String("squaremo"),
		})

		if err != nil {
			return err
		}

		_, err = mysql.NewDatabase(ctx, "mydb", nil, pulumi.Providers(prov))

		return err
	})
}
```

**Comment by squaremo** [comment]
OK, having consulted with my colleagues and peered at the code, I think we can do better with the code generation, to avoid this problem -- I've filed the issue linked just above.

**Comment by csakshaug** [comment]
Is this the same as @pierskarsenbarg and me have been looking into in [11086](https://github.com/pulumi/pulumi/issues/11086) ? 

I have been super happy if this could be fixed 🥇

**Comment by squaremo** [comment]
> Is this the same as @pierskarsenbarg and me have been looking into in https://github.com/pulumi/pulumi/issues/11086 ?

The symptom is exactly the same (blank proxy), and the diagnosis looks exactly the same (incorrect handling of defaults) -- yes it is! Let's keep the earlier posting, mention the underlying issue there, and mark this one as duplicate. @mpholcomb if I may redirect your attention over to https://github.com/pulumi/pulumi/issues/11086 ...
