### ISSUE TITLE
Pulumi secret for provider password

### ISSUE THREAD

**Issue by AshTharappel** [pulumi/pulumi-mysql#333]
https://github.com/pulumi/pulumi-mysql/blob/58628894155702f25f2de2184b615ca713ad6fd0/sdk/nodejs/provider.ts#L56

From Pulumi version 3.99 and on, passing in a pulumi.secret into the password argument does not actually treat the input as a secret. The password gets treated like plaintext, in job output and in state. 

I copied this from the postgres provider. 
`resourceInputs["password"] = (args === null || args === void 0 ? void 0 : args.password) ? pulumi.secret(args.password) : undefined;`

They are forcing every password in as a pulumi.secret. Could we update this mysql provider to also do the same thing to ensure that passwords aren't put into state files or job log outputs?

Here is the PR where the change was made on the postgres provider
https://github.com/pulumi/pulumi-postgresql/commit/a2955fef76db8d3c6d604bb2e9478eb6812d2bdf#diff-a76e1dad54d1c17ef14f8677be9b77dc86bdda21e1c62f2fef9d7e9a24e5f66dR200 

Thanks.

**Comment by iwahbe** [comment]
Hi @AshTharappel. I'm sorry this isn't working as expected. I am a little confused though.

The equivalent section of this provider is:

https://github.com/pulumi/pulumi-mysql/blob/58628894155702f25f2de2184b615ca713ad6fd0/sdk/nodejs/provider.ts#L56

[It has not changed for the past 3 years.](https://github.com/pulumi/pulumi-mysql/blame/58628894155702f25f2de2184b615ca713ad6fd0/sdk/nodejs/provider.ts#L56)

The latest release version of this provider is v3.2.1, and it is on Pulumi v.98.0:

https://github.com/pulumi/pulumi-mysql/blob/f02bd35bca106649f0e1d05e51ab41da282700b9/provider/go.mod#L8


Can you please post a reproduction: a code example with different behavior between versions, the old version and the new version?

**Comment by AshTharappel** [comment]
Hey @iwahbe, Thanks for getting back to me. 

I agree with you the code hasn't been touched in a while, but since y'all are pulling in latest for the pulumi dependency. There is a risk that a change that they make could affect this package. 
https://github.com/pulumi/pulumi-mysql/blob/master/sdk/nodejs/package.json#L16

### Here is examples of the unexpected behavior

Here the installed pulumi dependency for the mysql package is 3.102.0
![image](https://github.com/pulumi/pulumi-mysql/assets/14657284/5ea88965-aa86-44de-a53d-5118f7f68c6c)
_If you notice the path, at the top, that is the pulumi package inside the mysql package_

Here i am using the mysql provider package as it is normally installed and configured
Here is the code for creating the provider. 
![image](https://github.com/pulumi/pulumi-mysql/assets/14657284/416f012d-0138-43b2-b2cb-da3cd92df78a)

Here is the output of the preview diff
_Notice that the password is displayed in plain text even though I used a pulumi.secret in the input argument_
![image](https://github.com/pulumi/pulumi-mysql/assets/14657284/e4e5d51d-2147-4482-9937-141aca668728)

### Here is it working as expected on pulumi version 3.98.0

I manually pinned the version of pulumi in the mysql package to 3.98.0 and then ran yarn install from that directory
![image](https://github.com/pulumi/pulumi-mysql/assets/14657284/bcab5b70-ef6c-464e-9bfc-de68b342c89b)

I re-ran the pulumi preview diff, and now the password is being treated like the pulumi.secret that i passed into the arguments. 
![image](https://github.com/pulumi/pulumi-mysql/assets/14657284/489c6b83-c652-4c12-a53f-faa5676d9b5c)


### Heres an example of fixing it while keeping the pulumi version on the latest version 3.102.0

In this example i copied how the postgres provider handles the password field. 
_I'm honestly not sure what changed in the pulumi provider for this unexpected outcome, but i knew that the postgres provider was working as expected, so just went to their source code for help_

I removed my node_modules and reinstalled my packages to have the untouched mysql package and it's dependencies. 
I copied out the provider code from the package library, and put that into my codebase just changing the one line mentioned above. 
`resourceInputs["password"] = (args === null || args === void 0 ? void 0 : args.password) ? pulumi.secret(args.password) : undefined;`

Here is the preview diff output. 
![image](https://github.com/pulumi/pulumi-mysql/assets/14657284/30de9639-5398-4e05-8b28-a11cceb0c8e8)

It is forcing the inputs to always be a pulumi.secret.

Please let me know if there is any other information i can provide. 
Thanks for you help.

**Comment by iwahbe** [comment]
Hi @AshTharappel. I am unable to reproduce this issue. I have tried with the following program:

```json
{
    "name": "ts",
    "main": "index.ts",
    "devDependencies": {
        "@types/node": "^16"
    },
    "dependencies": {
        "@pulumi/pulumi": "3.102.0",
        "@pulumi/mysql": "3.2.1"
    }
}
```

```ts
import * as mysql from "@pulumi/mysql";
import { secret } from "@pulumi/pulumi";

const p = new mysql.Provider("mysql", {
    username: "name",
    password: secret("some-password"),
    endpoint: "something.rds",
})

export const password = p.password;
```

```sh
Do you want to perform this update? details
+ pulumi:pulumi:Stack: (create)
    [urn=urn:pulumi:dev::ts::pulumi:pulumi:Stack::ts-dev]
    + pulumi:providers:mysql: (create)
        [urn=urn:pulumi:dev::ts::pulumi:providers:mysql::mysql]
        endpoint: "something.rds"
        password: [secret]
        tls     : "false"
        username: "name"
        version : "3.2.1"

    --outputs:--
    password: [secret]
```

It seems to work as expected for me.

**Comment by AshTharappel** [comment]
Thank you so much for your time and your help. 

I was able to solve the problem i was having locally on my machine by upgrading my direct version of pulumi. 
_My version was set to 3.88, so apparently the version mismatch was causing this issue_

Once again thank you so much for your help. Sorry for the false issue.
