### ISSUE TITLE
'protect' does not exist in type 'InstanceArgs'

### ISSUE THREAD

**Issue by benjick** [pulumi/pulumi-mysql#52]
Following this guide https://www.pulumi.com/blog/managing-your-mysql-databases-with-pulumi/#example-2-using-a-rds-instance it lists `protect: true` as a property on the instance but it's not available on the interface.

```
Argument of type '{ engine: string; username: any; password: any; availabilityZone: string; instanceClass: string; allocatedStorage: number; protect: boolean; }' is not assignable to parameter of type 'InstanceArgs'.
  Object literal may only specify known properties, and 'protect' does not exist in type 'InstanceArgs'.ts(2345)
```

Version: 2.1.2

Looking at the interface I can see `deletionProtection` available

**Comment by stack72** [comment]
Hi @benjick 

You are correct - the property has since been updated to be `deletionProtection` - I am going to fix up the blog post now

Thanks

Paul
