### ISSUE TITLE
Hangs at 'creating' instead of error message

### ISSUE THREAD

**Issue by kralikba** [pulumi/pulumi-mysql#85]
Hi,
When trying to create a MySQL database/user on a MySQL 8.0 server, the operation hangs at `creating...`.
I'm using .net 5 / c# 9.
Combing through logs, I believe that the terraform provider itself is hanging - however I'm not a pulumi nor a terraform expert.
See a minimal complete non-working example at https://github.com/kralikba/pulumi-akv/tree/master/pulumi-az-mysql

**Comment by kralikba** [comment]
Apparently I have made a mistake with the username; I did not include a hostname part in it. This should result in a proper error message instead of the process hanging.

**Comment by mjeffryes** [comment]
looks like this question is resolved
